# Codecov Configuration for TOON4J
# ==================================

# Coverage configuration
coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 70%
        threshold: 2%
        if_ci_failed: error

    patch:
      default:
        target: 80%
        threshold: 5%

  changes:
    default:
      target: auto

# Comment configuration
comment:
  layout: "reach,diff,flags,tree,files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

# Ignore patterns
ignore:
  - "src/test/**/*"
  - "**/Example.java"
  - "**/Benchmark.java"
  - "**/PojoExample.java"
  - "**/PojoBenchmark.java"

# Flags for different test suites
flags:
  unittests:
    paths:
      - src/main/java/
    carryforward: true

# GitHub checks
github_checks:
  annotations: true

# Pull request settings
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no
